#' Fit time-dependent beta latent variable model
#'
#' @param btblv_data object btblv_data generated by the function `create_btblv_data`
#' @param K latent dimension size
#' @param precision string
#' @param iter integer
#' @param warmup integet
#' @param thin integet
#' @param chains integet
#' @param cores integet
#' @param seed integet
#' @param ... additional parameters for the `rstan::sampling` function
#'
#' @return object of the class btblv_fit
#' @export
#'
#' @examples
#' ##
btblv_fit = function(btblv_data,
                     K,
                     precision = "single",
                     iter,
                     warmup,
                     thin,
                     chains,
                     cores,
                     seed,
                     ...) {
  # add latent dimension K
  btblv_data$data_list_stan$K = K

  inits = .generate_init_values(
    btblv_data = btblv_data,
    K = K,
    chains = chains,
    precision = precision,
    seed = seed
  )

  pars = c("E", "theta", "alpha", "beta", "log_kappa",
           "phi", "sigma")

  if(precision == "single") {
    fit = rstan::sampling(
      stanmodels$time_BLV_single_precision,
      data = btblv_data$data_list_stan,
      iter = iter,
      warmup = warmup,
      thin = thin,
      chains = chains,
      cores = cores,
      init = inits,
      pars = pars,
      ...
    )

  }else if(precision == "multiple"){
    fit = rstan::sampling(
      stanmodels$time_BLV,
      data = btblv_data$data_list_stan,
      iter = iter,
      warmup = warmup,
      thin = thin,
      chains = chains,
      cores = cores,
      init = inits,
      pars = pars,
      ...
    )
  }

  out = list(
    stan_fit = fit,
    btblv_data = btblv_data
  )

  class(out) = "btblv_fit"


  return(out)
}
