#' Fit time-dependent beta latent variable model
#'
#' @param btblv_data object btblv_data generated by the function `create_btblv_data`.
#' @param K interger with the latent dimension size.
#' @param precision string with the type of precision. It is "single" if all
#' items have the same precision or "specific" if each item has its own precision
#' parameter. Default is "single".
#' @param iter integer with the number of iterations
#' @param warmup integer with the warmup size. See `rstan::sampling`.
#' @param thin integer with the thinning size. See `rstan::sampling`.
#' @param chains integer with the number of chains. See `rstan::sampling`.
#' @param cores integer with the number of cores running the chains. See `rstan::sampling`.
#' @param seed integer with the random seed.
#' @param ... additional parameters for the `rstan::sampling` function.
#'
#' @return object of the class btblv_fit
#' @export
#'
#' @examples
#' ##
btblv_fit = function(btblv_data,
                     K,
                     precision = "single",
                     iter,
                     warmup,
                     thin,
                     chains,
                     cores,
                     seed,
                     ...) {
  # add latent dimension K
  btblv_data$data_list_stan$K = K

  inits = .generate_init_values(
    btblv_data = btblv_data,
    K = K,
    chains = chains,
    precision = precision,
    seed = seed
  )

  pars = c("E", "theta", "alpha", "beta", "log_kappa",
           "phi", "sigma")

  if(precision == "single") {
    fit = rstan::sampling(
      stanmodels$time_BLV_single_precision,
      data = btblv_data$data_list_stan,
      iter = iter,
      warmup = warmup,
      thin = thin,
      chains = chains,
      cores = cores,
      init = inits,
      pars = pars,
      ...
    )

  }else if(precision == "specific"){
    fit = rstan::sampling(
      stanmodels$time_BLV,
      data = btblv_data$data_list_stan,
      iter = iter,
      warmup = warmup,
      thin = thin,
      chains = chains,
      cores = cores,
      init = inits,
      pars = pars,
      ...
    )
  }

  out = list(
    stan_fit = fit,
    btblv_data = btblv_data,
    precision = precision
  )

  class(out) = "btblv_fit"
  return(out)
}
