#' Check model fit
#'
#' Computes metrics for model fit like reconstruction RMSE, MAE and MAPE.
#'
#' @param posterior_predict `posterior_predict` object generated by `posterior_predict`.
#' @param posterior_summary `posteior_summary` object generated by `posterior_summary`.
#'
#' @return list with the elements:
#' \itemize{
#'   \item `global_metrics` - metrics for whole data.
#'   \item `item_metrics` - metrics grouped by item.
#'   \item `group_metrics` - metrics grouped by group.
#'   \item `distance_metrics` - metrics for the distance between the observations.
#' }
#'
#' @export
#'
#' @examples
#' #
check_fit = function(posterior_predict, posterior_summary) {

  pred_post_summary_df = posterior_predict$pred_post_summary_df

  observed_dist = pred_post_summary_df %>%
    dplyr::select(ind_num, item, y) %>%
    tidyr::spread(item, y) %>%
    dplyr::select(-ind_num) %>%
    stats::dist() %>%
    base::as.matrix() %>%
    .[base::lower.tri(.)]

  pred_post_dist = pred_post_summary_df %>%
    dplyr::select(ind_num, item, mean) %>%
    tidyr::spread(item, mean) %>%
    dplyr::select(-ind_num) %>%
    stats::dist() %>%
    base::as.matrix() %>%
    .[base::lower.tri(.)]

  latent_distance = posterior_summary$posterior_mean$theta %>%
    stats::dist() %>%
    as.matrix() %>%
    .[base::lower.tri(.)]

  distance_metrics = tibble::tibble(
    RMSE = sqrt(mean((observed_dist - pred_post_dist)^2)),
    MAE = mean(abs(observed_dist - pred_post_dist)),
    MAPE = 100*mean((abs(observed_dist - pred_post_dist)/abs(observed_dist))),
    corr = cor(latent_distance, observed_dist)
  )

  global_metrics = pred_post_summary_df %>%
    dplyr::summarise(RMSE = sqrt(mean((y - mean)^2)),
                     MAE = mean(abs(y - mean)),
                     MAPE = 100*mean((abs(y - mean)/abs(y))))

  item_metrics = pred_post_summary_df %>%
    dplyr::group_by(item) %>%
    dplyr::summarise(RMSE = sqrt(mean((y - mean)^2)),
                     MAE = mean(abs(y - mean)),
                     MAPE = 100*mean((abs(y - mean)/abs(y))))

  group_metrics = pred_post_summary_df %>%
    dplyr::group_by(group) %>%
    dplyr::summarise(RMSE = sqrt(mean((y - mean)^2)),
                     MAE = mean(abs(y - mean)),
                     MAPE = 100*mean((abs(y - mean)/abs(y))))

  check_metrics = list(
    global_metrics = global_metrics,
    item_metrics = item_metrics,
    group_metrics = group_metrics,
    distance_metrics = distance_metrics
  )

  return(check_metrics)
}



