#' Compute converge checks for posterior samples from the btblv model
#'
#' @param btblv_posterior `btblv_posterior` object generated by `extract_posterior`.
#'
#' @return data.frame with the the converge metrics
#' @export
#'
#' @examples
#' #
check_convergence = function(btblv_posterior) {

  beta = btblv_posterior$post_sample_chains$beta %>%
    .compute_converge_metrics() %>%
    dplyr::rename(item_num = id)

  if(btblv_posterior$precision == "single") {
    log_kappa = btblv_posterior$post_sample_chains$log_kappa %>%
      .compute_converge_metrics()

    kappa = btblv_posterior$post_sample_chains$log_kappa %>%
      exp() %>%
      .compute_converge_metrics()

  }else if(btblv_posterior$precision == "specific") {
    log_kappa = btblv_posterior$post_sample_chains$log_kappa %>%
      .compute_converge_metrics() %>%
      dplyr::rename(item_num = id)

    kappa = btblv_posterior$post_sample_chains$log_kappa %>%
      exp() %>%
      .compute_converge_metrics() %>%
      dplyr::rename(item_num = id)
    
    baseline_delta = btblv_posterior$post_sample_chains$baseline_delta %>%
      .compute_converge_metrics()
  }

  phi = btblv_posterior$post_sample_chains$phi %>%
    .compute_converge_metrics() %>%
    dplyr::rename(group_num = id)

  sigma = btblv_posterior$post_sample_chains$sigma %>%
    .compute_converge_metrics() %>%
    dplyr::rename(sigma_num = id)

  lp__ = btblv_posterior$post_sample_chains$lp__ %>%
    .compute_converge_metrics()

  alpha = btblv_posterior$post_sample_chains$rot_alpha %>%
    .compute_converge_metrics() %>%
    dplyr::rename(item_num = id)

  theta = btblv_posterior$post_sample_chains$rot_theta %>%
    .compute_converge_metrics() %>%
    dplyr::rename(ind_num = id)

  E = btblv_posterior$post_sample_chains$rot_E %>%
    .compute_converge_metrics() %>%
    dplyr::rename(ind_num = id)

  posterior_check_list = list(
    beta = beta,
    log_kappa = log_kappa,
    kappa = kappa,
    phi = phi,
    sigma = sigma,
    alpha = alpha,
    theta = theta,
    E = E
  )
  
  if(btblv_posterior$precision == "specific") {
    posterior_check_list$baseline_delta = baseline_delta
  }

  return(posterior_check_list)

}
