#' Check model fit
#'
#' Computes metrics for model fit like reconstruction RMSE, MAE and MAPE.
#'
#' @param posterior_predict `posterior_predict` object generated by `posterior_predict`.
#' @param posterior_summary `posteior_summary` object generated by `posterior_summary`.
#'
#' @return list with the elements:
#' \itemize{
#'   \item `global_metrics` - metrics for whole data.
#'   \item `item_metrics` - metrics grouped by item.
#'   \item `group_metrics` - metrics grouped by group.
#'   \item `distance_metrics` - metrics for the distance between the observations.
#' }
#'
#' @export
#'
#' @examples
#' #
check_fit = function(posterior_predict, posterior_summary) {

  pred_post_summary_df = posterior_predict$pred_post_summary_df

  observed_dist = pred_post_summary_df %>%
    dplyr::select(ind_num, item, y) %>%
    tidyr::spread(item, y) %>%
    dplyr::select(-ind_num) %>%
    stats::dist() %>%
    base::as.matrix() %>%
    .get_lower_tri()

  pred_post_dist = pred_post_summary_df %>%
    dplyr::select(ind_num, item, mean) %>%
    tidyr::spread(item, mean) %>%
    dplyr::select(-ind_num) %>%
    stats::dist() %>%
    base::as.matrix() %>%
    .get_lower_tri()

  latent_distance = posterior_summary$posterior_mean$theta %>%
    stats::dist() %>%
    as.matrix() %>%
    .get_lower_tri()

  distance_metrics = tibble::tibble(
    RMSE = .compute_RMSE(observed_dist, pred_post_dist),
    MAE = .compute_MAE(observed_dist, pred_post_dist),
    MAPE = .compute_MAPE(observed_dist, pred_post_dist),
    corr = cor(latent_distance, observed_dist, method = "spearman")
  )

  global_metrics = pred_post_summary_df %>%
    dplyr::summarise(RMSE = .compute_RMSE(y, mean),
                     MAE = .compute_MAE(y, mean),
                     MAPE = .compute_MAPE(y, mean))

  item_metrics = pred_post_summary_df %>%
    dplyr::group_by(item) %>%
    dplyr::summarise(RMSE = .compute_RMSE(y, mean),
                     MAE = .compute_MAE(y, mean),
                     MAPE = .compute_MAPE(y, mean))

  group_metrics = pred_post_summary_df %>%
    dplyr::group_by(group) %>%
    dplyr::summarise(RMSE = .compute_RMSE(y, mean),
                     MAE = .compute_MAE(y, mean),
                     MAPE = .compute_MAPE(y, mean))

  check_metrics = list(
    global_metrics = global_metrics,
    item_metrics = item_metrics,
    group_metrics = group_metrics,
    distance_metrics = distance_metrics
  )

  return(check_metrics)
}



