#' Compute WAIC based on the conditional likelihood
#'
#' @param btblv_posterior btblv_posterior btblv_posterior objected generated by `extract_posterior`.
#'
#' @return WAIC object from `loo::waic` package.
#' @export
#'
#' @examples
#' #
compute_WAIC = function(btblv_posterior) {
  log_like_matrix = extract_cond_log_like(btblv_posterior)
  cwaic = loo::waic(log_like_matrix)
  return(cwaic)
}

