#' Fit the time-dependent beta latent variable model with HMC
#'
#' @param btblv_data `btblv_data` object generated by the function `create_btblv_data`.
#' @param K integer with the latent dimension size.
#' @param precision string with the type of precision. It is "single" if all
#' items have the same precision or "specific" if each item has its own precision
#' parameter. Default is "single".
#' @param iter integer with the number of iterations
#' @param warmup integer with the warm-up size. See `rstan::sampling`.
#' @param thin integer with the thinning size. See `rstan::sampling`.
#' @param chains integer with the number of chains. See `rstan::sampling`.
#' @param cores integer with the number of cores running the chains. See `rstan::sampling`.
#' @param seed integer with the random seed.
#' @param ... additional parameters for the `rstan::sampling` function.
#'
#' @return object of the class `btblv_fit`.
#' @export
#'
#' @examples
#' ##
fit_btblv = function(btblv_data,
                     K,
                     precision = "single",
                     iter,
                     warmup,
                     thin,
                     chains,
                     cores,
                     seed,
                     ...) {
  # add latent dimension K
  btblv_data$data_list_stan$K = K

  inits = .generate_init_values(
    btblv_data = btblv_data,
    K = K,
    chains = chains,
    precision = precision,
    seed = seed
  )

  if(precision == "single") {

    fit = rstan::sampling(
      object = stanmodels$time_BLV_single_precision,
      data = btblv_data$data_list_stan,
      pars = c("beta_expand", "log_sigma", "kappa"),
      include = F,
      iter = iter,
      warmup = warmup,
      thin = thin,
      chains = chains,
      cores = cores,
      init = inits,
      ...
    )

  }else if(precision == "specific"){


    fit = rstan::sampling(
      object = stanmodels$time_BLV,
      data = btblv_data$data_list_stan,
      pars = c("beta_expand", "delta_raw", "log_sigma"),
      include = FALSE,
      iter = iter,
      warmup = warmup,
      thin = thin,
      chains = chains,
      cores = cores,
      init = inits,
      ...
    )

  }

  out = list(
    stan_fit = fit,
    btblv_data = btblv_data,
    precision = precision
  )

  class(out) = "btblv_fit"
  return(out)
}
