#' Transform result `Result_IMIFA` object to a object similar to `btblv_posterior` object.
#'
#' @param btblv_data data used to fit the IMIFA model applied to `btblv::create_btblv_data`.
#' @param imifa_result `Result_IMIFA` object generated by `IMIFA::get_IMIFA_results`.
#'
#' @return object `fa_imifa_posterior` similar to `btblv_posterior`. This object
#' can inherits the methods `btblv::posterior_summary` and `btblv::posterior_predict`.
#' @export
#'
#' @examples
#' #
imifa_to_blv = function(btblv_data, imifa_result) {
  alpha_dim = dim(imifa_result$Loadings$lmats$Cluster1)
  theta_dim = dim(imifa_result$Scores$eta)

  K = alpha_dim[2]
  J = alpha_dim[1]
  iters = alpha_dim[3]
  n = theta_dim[1]

  btblv_data$data_list_stan$K = K

  fix_mu = btblv_data$data_list_stan$x %>% log() %>% colMeans()

  beta = imifa_result$Means$mus$Cluster1 %>% t()

  for(j in 1:J) {
    beta[, j] = beta[, j] + fix_mu[j]
  }

  alpha = array(dim = c(iters, J, K))
  theta = array(dim = c(iters, n, K))
  kappa = imifa_result$Uniquenesses$psis$Cluster1 %>% t()

  for(k in 1:K) {
    alpha[, , k] = imifa_result$Loadings$lmats$Cluster1[, k, ] %>% t()
    theta[, , k] = imifa_result$Scores$eta[, k, ] %>% t()
  }

  post_sample_array = list()
  post_sample_array[["beta"]] = beta
  post_sample_array[["rot_alpha"]] = alpha
  post_sample_array[["rot_theta"]] = theta
  post_sample_array[["kappa"]] = kappa
  post_sample_array[["log_kappa"]] = kappa %>% log()

  post_sample_chains_list = list()

  for(param in names(post_sample_array)) {
    param_dim = dim(post_sample_array[[param]])
    post_sample_chains_list[[param]] = array(dim = c(param_dim, 1))
    if(length(param_dim) == 2) {
      post_sample_chains_list[[param]][,,1] = post_sample_array[[param]]
    }else if(length(param_dim) == 3) {
      post_sample_chains_list[[param]][,,,1] = post_sample_array[[param]]
    }
  }

  out = list(
    post_sample_array = post_sample_array,
    post_sample_chains = post_sample_chains_list,
    btblv_data = btblv_data,
    precision = "specific"
  )

  class(out) = c("fa_imifa_posterior")

  return(out)

}
