#' Posterior predictive sample and summary for the btblv model
#'
#' @param btblv_posterior `btblv_posterior` object generated by `extract_posterior`.
#' @param seed int seed for the random values.
#' @param cred_mass numeric value in the interval (0, 1) with the mass of the HPD interval.
#'
#' @return A list with the elements:
#' \itemize{
#'   \item `pred_post_summary_df` - `data.frame` with the group, time, item,
#'   and summary statistics for the observation.
#'   \item `pred_post_sample` - matrix (iteration x observations) with the posterior predictive sample.
#' }
#' @export
#'
#' @examples
#' # example_fit$single_K1 %>% extract_posterior() %>% posterior_predict()
posterior_predict = function(btblv_posterior, seed, cred_mass = 0.95) {

  set.seed(seed)

  iters = btblv_posterior$post_sample_array$beta %>% dim() %>% .[1]
  N = btblv_posterior$btblv_data$data_list_stan$N

  pred_post_sample = matrix(nrow = iters, ncol = N)

  theta = btblv_posterior$post_sample_array$rot_theta
  alpha = btblv_posterior$post_sample_array$rot_alpha
  beta = btblv_posterior$post_sample_array$beta
  kappa = btblv_posterior$post_sample_array$kappa
  precision = btblv_posterior$precision

  item = btblv_posterior$btblv_data$data$item_num
  ind = btblv_posterior$btblv_data$data$ind_num

  if(class(btblv_posterior) == "btblv_posterior") {

    for(i in 1:iters) {

      mu_iter = rowSums(cbind(alpha[i, item, ] * theta[i, ind, ])) + beta[i, item]
      mu_iter = inv_logit(mu_iter)

      if(precision == "single") {
        kappa_iter = kappa[i]
      }else{
        kappa_iter = kappa[i, item]
      }

      pred_post_sample[i, ] = rbeta(N, mu_iter*kappa_iter, (1-mu_iter)*kappa_iter)
    }

  }else if(class(btblv_posterior) == "fa_imifa_posterior") {

    for(i in 1:iters) {

      mu_iter = rowSums(cbind(alpha[i, item, ] * theta[i, ind, ])) + beta[i, item]

      if(precision == "single") {
        kappa_iter = kappa[i]
      }else{
        kappa_iter = kappa[i, item]
      }

      pred_post_sample[i, ] = rnorm(N, mu_iter, sqrt(kappa_iter)) %>% exp()

    }
  }

  pred_post_summary_df = tibble::tibble(
    ind_num = btblv_posterior$btblv_data$data$ind_num,
    group = btblv_posterior$btblv_data$data$group,
    time = btblv_posterior$btblv_data$data$time,
    item = btblv_posterior$btblv_data$data$item,
    y = btblv_posterior$btblv_data$data$y,
    mean = pred_post_sample %>% colMeans(),
    sd = pred_post_sample %>% apply(MARGIN = 2, FUN = sd),
    li = pred_post_sample %>% apply(MARGIN = 2, function(x) HDInterval::hdi(x, credMass = cred_mass)[1]),
    median = pred_post_sample %>% apply(MARGIN = 2, FUN = median),
    ui = pred_post_sample %>% apply(MARGIN = 2, function(x) HDInterval::hdi(x, credMass = cred_mass)[2])
  )

  out = list(
    pred_post_summary_df = pred_post_summary_df,
    pred_post_sample = pred_post_sample,
    seed = seed
  )

  return(out)
}






