#' Compute posterior summary for the btblv_posterior object
#'
#' @param btblv_posterior object of the class btblv_posterior generated by `extract_posterior`
#'
#' @return posterior summary
#' @export
#'
#' @examples
#' #
posterior_summary = function(btblv_posterior) {
  posterior_mean = list(
    alpha = .compute_posterior_mean(btblv_posterior$post_sample_array$rot_alpha),
    beta = .compute_posterior_mean(btblv_posterior$post_sample_array$beta),
    kappa = .compute_posterior_mean(btblv_posterior$post_sample_array$log_kappa %>% exp()),
    theta = .compute_posterior_mean(btblv_posterior$post_sample_array$rot_theta),
    E = .compute_posterior_mean(btblv_posterior$post_sample_array$rot_E),
    phi = .compute_posterior_mean(btblv_posterior$post_sample_array$phi),
    sigma = .compute_posterior_mean(btblv_posterior$post_sample_array$sigma)
  )

  return(posterior_mean)
}
