#' Generate data from the btblv model based on the posterior mean of the parameters
#'
#' @param btblv_posterior object of the class `btblv_posterior` generated by `extract_posterior`.
#' @param replicates integer value with the number of replicates.
#' @param seed int seed for the random values.
#'
#' @return list
#' @export
#'
#' @examples
#' #
simulate_data = function(btblv_posterior, replicates, seed) {

  set.seed(seed)

  post_summary = btblv_posterior %>% btblv::posterior_summary()
  btblv_data = btblv_posterior$btblv_data

  E = post_summary$posterior_mean$E
  phi = post_summary$posterior_mean$phi
  sigma = post_summary$posterior_mean$sigma
  beta = post_summary$posterior_mean$beta
  kappa = post_summary$posterior_mean$kappa
  alpha = post_summary$posterior_mean$alpha

  if(btblv_posterior$precision == "single") {
    kappa = kappa * (beta/beta)
  }

  group_index = btblv_data$data_wide$group_num

  theta = .apply_increment_to_series(
    E = E,
    group_index = group_index,
    sigma = sigma,
    phi = phi
  )

  J = btblv_data$data_list_stan$J
  K = btblv_data$data_list_stan$K
  Ng = btblv_data$data_list_stan$Ng
  n = btblv_data$data_list_stan$n
  N = btblv_data$data_list_stan$N

  mu_df = inv_logit(theta%*%t(alpha) + (matrix(1, n) %x% t(beta)))
  mu_df = as.data.frame(mu_df)

  true_beta_params = btblv_data$data_wide %>%
    dplyr::select(ind_num:time_num) %>%
    bind_cols(
      mu_df
    ) %>%
    tidyr::gather(item_num, mu, -ind_num, -group_num, -time_num) %>%
    dplyr::mutate(item_num = stringr::str_remove(item_num, "V") %>% as.integer()) %>%
    dplyr::left_join(
      data.frame(
        kappa = kappa %>% as.numeric(),
        item_num = 1:J
      ),
      by = "item_num"
    ) %>%
    dplyr::arrange(group_num, time_num, item_num) %>%
    dplyr::select(ind_num, item_num, group_num, time_num, mu, kappa) %>%
    dplyr::right_join(
      btblv_data$data,
      by=c("item_num", "ind_num", "group_num", "time_num")
    ) %>%
    dplyr::select(item, group, time, mu, kappa)

  # generate data from the beta
  sim_data_list = purrr::map(1:replicates, ~{
    true_beta_params = true_beta_params %>%
      dplyr::mutate(y = rbeta(n=N, mu*kappa, (1-mu)*kappa)) %>%
      dplyr::select(-mu, -kappa)

    names(true_beta_params) = btblv_data$columns

    true_beta_params

  })

  post_summary$posterior_mean$theta = theta

  out = list(
    sim_data_list = sim_data_list,
    btblv_data = btblv_data,
    true_parameters = post_summary$posterior_mean,
    true_parameters_df = post_summary$posterior_summary_df,
    seed = seed
  )

  return(out)
}




