# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_mc_log_mlike <- function(N, x, alpha, beta, kappa, phi, sigma, E_post_sample_list) {
    .Call(`_tblvArmaUtils_rcpp_mc_log_mlike`, N, x, alpha, beta, kappa, phi, sigma, E_post_sample_list)
}

LSE <- function(x) {
    .Call(`_tblvArmaUtils_LSE`, x)
}

