# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnrm_arma_fast <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_tblvArmaUtils_dmvnrm_arma_fast`, x, mean, sigma, logd)
}

LSE <- function(x) {
    .Call(`_tblvArmaUtils_LSE`, x)
}

rcpp_mc_log_mlike <- function(N, x, alpha, beta, kappa, phi, sigma, E_post_sample_list) {
    .Call(`_tblvArmaUtils_rcpp_mc_log_mlike`, N, x, alpha, beta, kappa, phi, sigma, E_post_sample_list)
}

rcpparma_hello_world <- function() {
    .Call(`_tblvArmaUtils_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_tblvArmaUtils_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_tblvArmaUtils_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_tblvArmaUtils_rcpparma_bothproducts`, x)
}

