# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('_armatblv_rcpparma_hello_world', PACKAGE = 'armatblv')
}

rcpparma_outerproduct <- function(x) {
    .Call('_armatblv_rcpparma_outerproduct', PACKAGE = 'armatblv', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_armatblv_rcpparma_innerproduct', PACKAGE = 'armatblv', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_armatblv_rcpparma_bothproducts', PACKAGE = 'armatblv', x)
}

LSE <- function(x) {
    .Call('_armatblv_LSE', PACKAGE = 'armatblv', x)
}

expand_vec <- function(x, n) {
    .Call('_armatblv_expand_vec', PACKAGE = 'armatblv', x, n)
}

mc_mlog_like <- function(N, x, alpha, beta, kappa, phi, sigma, E_post_sample_list) {
    .Call('_armatblv_mc_mlog_like', PACKAGE = 'armatblv', N, x, alpha, beta, kappa, phi, sigma, E_post_sample_list)
}

